### PR TITLE
Upgrade mailboxer sample app to the most recent version of Rails. Update therubyracer gem.

### PR DESCRIPTION
**Pull request by AlJohri**

### CODE REVIEW

**Comment by RKushnir** [comment]
Hi, @AlJohri. Thanks for the PR.
In fact, Rails 3.2.13 isn't the most recent version. Even ignoring the 4.x, there's a 3.2.14 already, so we better have it updated to the maximum. Change the version to 3.2.14, please, and I'll merge.

**Comment by RKushnir** [comment]
I just checked, mailboxer doesn't work with R4, so only 3.2 for now.

**Comment by AlJohri** [comment]
Updated to Rails 3.2.14.

However, the new maintainer has made the gem compatible with Rails 4. https://github.com/ging/mailboxer/issues/180

**Comment by RKushnir** [comment]
Hi @AlJohri
Please update the `Gemfile.lock` and squash the commits.

**Pull request closed without merging**
